# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-03 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics', '0007_instructortabsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructortabsconfig',
            name='add_info',
            field=models.BooleanField(default=True, verbose_name='Additional Info'),
        ),
    ]
