# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-10 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('rg_instructor_analytics', '0009_auto_20200810_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='total users')),
                ('empty', models.PositiveIntegerField(default=0, verbose_name='no data')),
                ('values', jsonfield.fields.JSONField(blank=True)),
                ('date', models.DateField(verbose_name='date')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_stats', to='sites.Site')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'education level statistics',
                'verbose_name_plural': 'education level statistics',
            },
        ),
        migrations.AlterUniqueTogether(
            name='educationstats',
            unique_together=set([('site', 'date')]),
        ),
    ]
