# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-17 09:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics', '0012_auto_20200810_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agestats',
            options={'ordering': ['date'], 'verbose_name': 'age statistics', 'verbose_name_plural': 'age statistics'},
        ),
        migrations.AlterModelOptions(
            name='educationstats',
            options={'ordering': ['date'], 'verbose_name': 'education statistics', 'verbose_name_plural': 'education statistics'},
        ),
        migrations.AlterModelOptions(
            name='residencestats',
            options={'ordering': ['date'], 'verbose_name': 'geo statistics', 'verbose_name_plural': 'geo statistics'},
        ),
    ]
